### ISSUE TITLE
Wrong references in the FHIR data

### ISSUE THREAD

**Issue by michelemottini** [smart-on-fhir/bulk-data-server#12]
The references uris are now `urn:uuid:<guid>`, instead they should be `<type>/<guid>`.

See https://github.com/smart-on-fhir/fhir-bulk-data-docs/issues/69

**Comment by vlad-ignatov** [comment]
The references are now converted to `ResourceType/id`.

**Comment by michelemottini** [comment]
It seems that there is something wrong: I get encounters containing 

```
"subject": { "reference": "Patient/o5-517c31b6-7969-47e4-ad1d-42afa51d3473" }
```

should be 

```
"subject": { "reference": "Patient/517c31b6-7969-47e4-ad1d-42afa51d3473" }
```

**Comment by vlad-ignatov** [comment]
That should be fine. This server is a little tricky. It only has 100 patients in the DB. If you specify in the UI that you want bigger DB, then it will loop over these 100 but prefix their IDs with something (like "o5-" in this case). In other words `Patient/o5-517c31b6-7969-47e4-ad1d-42afa51d3473` is a modified copy of `Patient/517c31b6-7969-47e4-ad1d-42afa51d3473` and for you those are 2 different resources.

**Comment by vlad-ignatov** [comment]
Got it. That happens when the referencing resource is virtual (has prefixed id). Then the same prefix is applied to the references. It might take some time to find a reasonable solution to this one :(

**Comment by vlad-ignatov** [comment]
Turns out it was not that complicated. Now only the `id` properties of the JSON objects are prefixed and references should always point to original resources.

**Comment by michelemottini** [comment]
Works nicely now, thanks
