### ISSUE TITLE
Missing referenced Encounter in the data 

### ISSUE THREAD

**Issue by michelemottini** [smart-on-fhir/bulk-data-server#13]
For example: 

```
{"resourceType":"Condition","id":"o1-a02d1fb0-da2f-477b-87eb-08f83853cdbc","clinicalStatus":"resolved","verificationStatus":"confirmed","code":{"coding":[{"system":"http://snomed.info/sct","code":"65363002","display":"Otitis media"}],"text":"Otitis media"},"subject":{"reference":"Patient/163950fe-3224-4607-80e7-0ff35ab44b21"},"context":{"reference":"Encounter/0e787dd7-e5f5-497a-a702-09a7945fc92a"},"onsetDateTime":"2013-09-10T09:10:16+00:00","abatementDateTime":"2014-09-27T09:10:16+00:00","assertedDate":"2013-09-10T09:10:16+00:00"}
```

references `Encounter/0e787dd7-e5f5-497a-a702-09a7945fc92a` but there is no encounter with such an ID in the Encounter file. There appear to be a bunch of Condition and Immunization with this problem

**Comment by vlad-ignatov** [comment]
This might be fixed now. It is very difficult to test though. I wrote a validation script that is now part of the sample client (see https://github.com/smart-on-fhir/sample-apps-stu3/tree/master/fhir-downloader#validating-references). It is still interesting to see if this passes more realistic use cases like yours.

**Comment by michelemottini** [comment]
I tried again but now I cannot authenticate any more: ` invalid_grant - No public keys found in the JWKS with "kid" equal to "6662F2F81C1A45A7153DDB75C822B6673E6E7A29" and "kty" equal to "undefined"`

I am using the client_id:

```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InJlZ2lzdHJhdGlvbi10b2tlbiJ9.eyJqd2tzX3VybCI6Imh0dHA6Ly9kZW1vLmNhcmVldm9sdXRpb24uY29tL0NOand0Y2FyZWV2b2x1dGlvbmNvbS5qc29uIiwiYWNjZXNzVG9rZW5zRXhwaXJlSW4iOjE1LCJpYXQiOjE1MzcyODU5Nzl9.tIYhaCKunQ-OiQNA15wIvomihsScKQED4oycIbEqIFU
```

**Comment by vlad-ignatov** [comment]
Yes, those are some breaking changes from https://github.com/smart-on-fhir/fhir-bulk-data-docs/pull/77. You are now expected to pass `kty` token header (instead of `alg`)

**Comment by michelemottini** [comment]
Ah yes, I forgot, sorry.

Works fine now, all references match.
