### ISSUE TITLE
If the initial request uses auth... all subsequent requests should, too

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/bulk-data-server#2]
Right now the following works, and shouldn't:

1. Kick off an export using an authorization header
2. Fetch status and data *without* an authorization header

I  had a bug in my client code where I forgot to include an authz header in my data fetch requests, and they worked anyway -- which made it hard to discover my bug :-)

**Comment by vlad-ignatov** [comment]
This is now implemented. There are tests for it and also the `requiresAccessToken` works as it should.
