### ISSUE TITLE
Build error on sqlite3

### ISSUE THREAD

**Issue by yunwwang** [smart-on-fhir/bulk-data-server#24]
Related to https://github.com/smart-on-fhir/bulk-data-server/issues/15

I downgrade node to 8.17 and still have the same build error

gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/yunweiw/Documents/GitHub/bulk-data-server/node_modules/sqlite3/lib/binding/node-v57-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/yunweiw/Documents/GitHub/bulk-data-server/node_modules/sqlite3/lib/binding/node-v57-darwin-x64"
gyp ERR! cwd /Users/yunweiw/Documents/GitHub/bulk-data-server/node_modules/sqlite3
gyp ERR! node -v v8.17.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok

**Comment by vlad-ignatov** [comment]
This has now been updated to support any Node version between 9 and 13 inclusive. Hope that helps.
