### ISSUE TITLE
Fetching large payloads goes slowly; node pegs the CPU

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/bulk-data-server#3]
```
curl -o /dev/null http://localhost:9443/eyJlcnIiOiIiLCJwYWdlIjoxMDAwMDAwLCJkdXIiOjAsInRsdCI6MTUsIm0iOjEwMDAwLCJyZXF1ZXN0U3RhcnQiOjE1MTcxNTIxMTY3MTEsIm9mZnNldCI6NDAwMDAwMDAsImxpbWl0IjoxMDAwMDAwfQ/fhir/bulkfiles/41.Observation.ndjson
```

Shows that speed goes ~80-200 kb/s on my link machine and on @gotdan's Mac. Node is pegged to 100% CPU.  This is surprising! There may be an opportunity to load more data into memory and issue fewer sqlite calls :-)

**Comment by vlad-ignatov** [comment]
The streaming part was re-implemented for higher throughput. I can download from my localhost with more than 30MB/s. That is off course "do as much as you can" type of solution so it does take 100% CPU. That is why there is a "throttle" config option that is set to `1` by default. This keeps the CPU at about 10% and the download speed is about 580kb/s.
