### ISSUE TITLE
Server requires kty in client_assertion header, but this isn't required in the IG

### ISSUE THREAD

**Issue by gotdan** [smart-on-fhir/bulk-data-server#37]
The server appears to be requiring a kty header: 
https://github.com/smart-on-fhir/bulk-data-server/blob/09235070ddb6c0f8fb828bddff76c7a6154801ac/token_handler.js#L200

However, this doesn't appear to be required in the IG:
 https://hl7.org/fhir/uv/bulkdata/authorization/index.html#protocol-details and

**Comment by vlad-ignatov** [comment]
Looking at the code, it seems to me that `kty` is no longer required (that line is commented). However, the comment and the error message need to be updated to reflect that.

I wonder if I'm missing something though. How did you discover this?

**Comment by gotdan** [comment]
My bad - I must have accidentally run an old version of the server that still had this issue!
