### ISSUE TITLE
Is the readme outdated for required Node version?

### ISSUE THREAD

**Issue by kyrlon** [smart-on-fhir/bulk-data-server#70]
Readme states that node works on 7.9, 8 and 9. However, I see there was a [commit](https://github.com/smart-on-fhir/bulk-data-server/commit/3577e0b8c58eec01471ef9af8ec604a9531ee7ac) stating an update to the package.json requiring node >= 20+.

**Comment by vlad-ignatov** [comment]
Fixed, Thanks!
